version: '3.4'

networks: 
  stdm_nginx_overlay:
    external: true

services:
  webapp:
    image: nginx:latest
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginxconf:/etc/nginx/conf.d
      - ./nginx/nginxcerts/certs:/home/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - stdm_nginx_overlay
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
